export const PROPERTIES = [
  {
    id: 'pune-persistent',
    name: 'Persistent Systems IT Park',
    location: 'Hinjewadi Phase 2, Pune',
    city: 'Pune',
    state: 'Maharashtra',
    sqft: 18500,
    value: 12,
    raised: 8.76,
    target: 12,
    grossYield: 9.2,
    netYield: 7.8,
    leaseYears: 6.5,
    tenant: 'Persistent Systems',
    tenantRating: 'AA+',
    tenantType: 'IT / GCC',
    status: 'open',
    fundedPct: 73,
    investors: 327,
    valuer: 'CBRE',
    valuationDate: 'Jan 2025',
    spv: 'RC Pune 001 Pvt Ltd',
    ticker: 'RC-PUNE-001',
    navPerUnit: 107800,
    navChange: 0.3,
    nextDist: 'Jul 1, 2026',
    distPerUnit: 1825,
    oc: true,
    rera: true,
    tags: ['IT Park', 'GCC', 'Hinjewadi'],
  },
  {
    id: 'nagpur-amazon',
    name: 'Amazon Fulfillment Warehouse',
    location: 'MIHAN SEZ, Nagpur',
    city: 'Nagpur',
    state: 'Maharashtra',
    sqft: 32000,
    value: 12,
    raised: 10.92,
    target: 12,
    grossYield: 10.4,
    netYield: 8.9,
    leaseYears: 8.0,
    tenant: 'Amazon India',
    tenantRating: 'AAA',
    tenantType: 'Logistics / E-commerce',
    status: 'open',
    fundedPct: 91,
    investors: 412,
    valuer: 'JLL',
    valuationDate: 'Feb 2025',
    spv: 'RC Nagpur 002 Pvt Ltd',
    ticker: 'RC-NGP-002',
    navPerUnit: 107800,
    navChange: 0.7,
    nextDist: 'Jul 1, 2026',
    distPerUnit: 1825,
    oc: true,
    rera: true,
    tags: ['Warehouse', 'Logistics', 'SEZ'],
  },
  {
    id: 'surat-hdfc',
    name: 'HDFC Bank Branch Complex',
    location: 'Ring Road, Surat',
    city: 'Surat',
    state: 'Gujarat',
    sqft: 8200,
    value: 6.5,
    raised: 6.5,
    target: 6.5,
    grossYield: 8.8,
    netYield: 7.4,
    leaseYears: 5.5,
    tenant: 'HDFC Bank',
    tenantRating: 'AAA',
    tenantType: 'Banking / BFSI',
    status: 'funded',
    fundedPct: 100,
    investors: 185,
    valuer: 'CBRE',
    valuationDate: 'Dec 2024',
    spv: 'RC Surat 003 Pvt Ltd',
    ticker: 'RC-SRT-003',
    navPerUnit: 104500,
    navChange: 0.1,
    nextDist: 'Jul 1, 2026',
    distPerUnit: 1540,
    oc: true,
    rera: true,
    tags: ['Bank Branch', 'BFSI', 'Ring Road'],
  },
  {
    id: 'coimbatore-dmart',
    name: 'D-Mart Retail Plaza',
    location: 'Avinashi Road, Coimbatore',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    sqft: 22000,
    value: 18,
    raised: 0,
    target: 18,
    grossYield: 11.2,
    netYield: 9.6,
    leaseYears: 9.0,
    tenant: 'D-Mart (Avenue Supermarts)',
    tenantRating: 'AA+',
    tenantType: 'Retail / FMCG',
    status: 'coming',
    fundedPct: 0,
    investors: 0,
    valuer: 'JLL',
    valuationDate: 'TBD',
    spv: 'TBD',
    ticker: 'RC-CBE-004',
    navPerUnit: 100000,
    navChange: 0,
    nextDist: 'TBD',
    distPerUnit: 0,
    oc: false,
    rera: false,
    tags: ['Retail', 'FMCG', 'South India'],
    opensDate: 'Aug 2026',
  },
]

export const PORTFOLIO_HOLDINGS = [
  { propertyId: 'pune-persistent', units: 20, invested: 2000000, currentNav: 2156000, income: 156000, xirr: 7.8 },
  { propertyId: 'nagpur-amazon', units: 10, invested: 1000000, currentNav: 1078000, income: 78000, xirr: 8.9 },
]

export const DISTRIBUTIONS = [
  { date: 'Apr 1, 2026', property: 'Pune IT Park', amount: 36500, type: 'Quarterly rent', paid: true },
  { date: 'Apr 1, 2026', property: 'Nagpur Warehouse', amount: 18250, type: 'Quarterly rent', paid: true },
  { date: 'Jan 1, 2026', property: 'Pune IT Park', amount: 36500, type: 'Quarterly rent', paid: true },
  { date: 'Jan 1, 2026', property: 'Nagpur Warehouse', amount: 18250, type: 'Quarterly rent', paid: true },
  { date: 'Oct 1, 2025', property: 'Pune IT Park', amount: 36500, type: 'Quarterly rent', paid: true },
]

export const ORDER_BOOK = {
  'pune-persistent': {
    buys: [
      { price: 107500, units: 3 },
      { price: 107200, units: 5 },
      { price: 106800, units: 2 },
    ],
    sells: [
      { price: 108000, units: 2 },
      { price: 108400, units: 4 },
      { price: 109000, units: 1 },
    ],
  },
  'nagpur-amazon': {
    buys: [
      { price: 107600, units: 4 },
      { price: 107000, units: 6 },
    ],
    sells: [
      { price: 108200, units: 3 },
      { price: 108800, units: 2 },
    ],
  },
}

export const IOT_DATA = [
  { property: 'Pune IT Park', healthScore: 87, hvac: 92, electrical: 95, fire: 100, alert: false },
  { property: 'Nagpur Warehouse', healthScore: 74, hvac: 71, electrical: 88, fire: 98, alert: true, alertMsg: 'HVAC unit 2 — scheduled maintenance overdue' },
]
